/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.VitalSign;
import Model.VitalSignHistory;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    VitalSignHistory history;
    public CreateJPanel(VitalSignHistory vsh) {
        initComponents();
        this.history=vsh;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fieldDate = new javax.swing.JTextField();
        fieldTemperature = new javax.swing.JTextField();
        fieldBp = new javax.swing.JTextField();
        fieldPulse = new javax.swing.JTextField();
        btnYes = new javax.swing.JRadioButton();
        btnNo = new javax.swing.JRadioButton();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel1.setText("Create Vital Sign");
        jLabel1.setBounds(190, 100, 200, 30);
        add(jLabel1);

        jLabel2.setText("Date");
        jLabel2.setBounds(150, 160, 50, 20);
        add(jLabel2);

        jLabel3.setText("Temperature");
        jLabel3.setBounds(110, 200, 80, 20);
        add(jLabel3);

        jLabel4.setText("Blood Pressure");
        jLabel4.setBounds(100, 240, 90, 20);
        add(jLabel4);

        jLabel5.setText("Pulse");
        jLabel5.setBounds(150, 280, 50, 20);
        add(jLabel5);

        jLabel6.setText("Conscious Status");
        jLabel6.setBounds(90, 320, 100, 20);
        add(jLabel6);
        
        fieldDate.setBounds(240, 160, 180, 25);
        add(fieldDate);

        fieldTemperature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldTemperatureActionPerformed(evt);
            }
        });
        fieldTemperature.setBounds(240, 200, 180, 25);
        add(fieldTemperature);
        
        fieldBp.setBounds(240, 240, 180, 25);
        add(fieldBp);

        fieldPulse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPulseActionPerformed(evt);
            }
        });
        fieldPulse.setBounds(240, 280, 180, 25);
        add(fieldPulse);

        buttonGroup1.add(btnYes);
        btnYes.setSelected(true);
        btnYes.setText("Yes");
        btnYes.setBounds(240, 320, 60, 25);
        add(btnYes);

        buttonGroup1.add(btnNo);
        btnNo.setText("No");
        btnNo.setBounds(240, 350, 60, 25);
        add(btnNo);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        btnSave.setBounds(270, 410, 80, 30);
        add(btnSave);
    }// </editor-fold>//GEN-END:initComponents

    private void fieldTemperatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTemperatureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldTemperatureActionPerformed

    private void fieldPulseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPulseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPulseActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
            String date=fieldDate.getText();
            float temp = Float.parseFloat(fieldTemperature.getText());
            double bloodPressure =Double.parseDouble(fieldBp.getText());
            int pulse =Integer.parseInt(fieldPulse.getText());
            boolean isConscious;
           
           if (btnYes.isSelected()){
               isConscious=true;
           }else{
               isConscious=false;
           }
           
           VitalSign vs=history.addNewVital();
           vs.setDate(date);
           vs.setTemperature(temp);
           vs.setBloodPressure(bloodPressure);
           vs.setPulse(pulse);
           vs.setIsConcious(isConscious);
      
            JOptionPane.showMessageDialog(this,"New VitalSign added","Success",JOptionPane.INFORMATION_MESSAGE);

            fieldDate.setText("");
            fieldBp.setText("");
            fieldPulse.setText("");
            fieldTemperature.setText("");

// TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnNo;
    private javax.swing.JButton btnSave;
    private javax.swing.JRadioButton btnYes;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField fieldBp;
    private javax.swing.JTextField fieldDate;
    private javax.swing.JTextField fieldPulse;
    private javax.swing.JTextField fieldTemperature;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
